### ISSUE TITLE
Add suport for php-cs-fixer version 3

### ISSUE THREAD

**Issue by xyfantis** [OVYA/php-cs-fixer#14]
php-cs-fixer has released a v3 version

https://github.com/FriendsOfPhp/PHP-CS-Fixer/tree/v3.0.0

upgrading results in 

Warning (emacs): Command php-cs-fixer version not supported.
Fix this issue removing the Emacs package php-cs-fixer or updating the program php-cs-fixer to version 2.*

**Comment by pivaldi** [comment]
@xyfantis Thank you for informing me of this update.

**Comment by fiskhandlarn** [comment]
@pivaldi any chance of getting https://github.com/OVYA/php-cs-fixer/commit/9e25dfbbf22fa3d2755a36d48bd4d6d1bbed5c5b into a release?

**Comment by pivaldi** [comment]
Hello,

It's done : https://github.com/OVYA/php-cs-fixer/tags
Thank you for taking the time to remind me this point.

Regards

> @pivaldi any chance of getting https://github.com/OVYA/php-cs-fixer/commit/9e25dfbbf22fa3d2755a36d48bd4d6d1bbed5c5b into a release?
-- 
PI
