### ISSUE TITLE
Package cl is deprecated

### ISSUE THREAD

**Issue by ziwot** [OVYA/php-cs-fixer#15]
Hello, I'm trying to customize the config file in a doom emacs, and can't have it working.

Maybe it's because of this deprecation?

Ref: https://github.com/alphapapa/org-protocol-capture-html/issues/41#issue-707497218
Doom ref: https://github.com/hlissner/doom-emacs/issues/3372

**Comment by ziwot** [comment]
The package is working correctly with custom config! 
I removed the finder from the file :facepalm: 

There is still an error, but it's relative to doom emacs I guess (https://github.com/hlissner/doom-emacs/issues/4613)

I left the issue open, but it might be closed as the package deprecation is just a warning

**Comment by bzzhh** [comment]
Hello, little update I solved the "args-out-of-range 0 0" error
Maybe there's a # missing on the doc or it should be:
`(add-hook! 'before-save-hook #'php-cs-fixer-before-save)`
Sorry still learning, so not sure, but I share it just in case it helps someone
