### ISSUE TITLE
"psr0" is renamed

### ISSUE THREAD

**Issue by fiskhandlarn** [OVYA/php-cs-fixer#19]
I'm getting this warning from php-cs-fixer as of latest release of this repo:

> Warning (emacs): No syntax errors detected in c:/Users/oskar/AppData/Local/Temp/PHP-CS-Fixer3B1aKE.php
> In ConfigurationResolver.php line 784:
>  The rules contain unknown fixers: "psr0" is renamed (did you mean "psr_autoloading"? (note: use configuration "[’dir’ => ’x’]")).                                                                                                       
>   For more info about updating see: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.0.0/UPGRADE-v3.md#renamed-rules.

Not sure where this originates from, the only place I can find "psr0" is [here](https://github.com/OVYA/php-cs-fixer/blob/7e12a1af5d65cd8a801eeb5564c6268a4e190c0c/php-cs-fixer.el#L135).

My versions:

> GNU Emacs 27.2 (build 1, x86_64-w64-mingw32)

> php-cs-fixer-20220510.1407

```bash
$ php-cs-fixer.bat -V
PHP CS Fixer 3.8.0 BerSzcz against war! by Fabien Potencier and Dariusz Ruminski.
PHP runtime: 7.4.27
```

My .emacs contents for this repo:

```elisp
(custom-set-variables
 '(package-selected-packages
   '(php-cs-fixer))
 '(php-cs-fixer-command "php-cs-fixer.bat")
 '(php-cs-fixer-rules-fixer-part-options nil)
 '(php-cs-fixer-rules-level-part-options '("@PSR12"))
)

(add-hook 'before-save-hook 'php-cs-fixer-before-save)
```

**Comment by pivaldi** [comment]
Thank you @fiskhandlarn to report this problem. Version 2.0.0 fixes it !
