### ISSUE TITLE
Include package into the MELPA archive

### ISSUE THREAD

**Issue by rubenrua** [OVYA/php-cs-fixer#4]
From https://melpa.org/ site:

> #### Adding a Package
> In so many words, fork the project's source tree and create a pull request with a recipe for your package. The README.md file on GitHub has more details. See the next section for a link.
>

**Comment by pivaldi** [comment]
Pull request to Melpa : https://github.com/melpa/melpa/pull/4732

**Comment by rubenrua** [comment]
Thank you

**Comment by pivaldi** [comment]
Pull request accepted : https://github.com/melpa/melpa/commit/a3631c4b81c1784995ae9e74d832e301d79214e2

Thank you for your suggestion.
