### ISSUE TITLE
Doesn't work on Windows

### ISSUE THREAD

**Issue by fiskhandlarn** [OVYA/php-cs-fixer#6]
I'm running Windows 10, Emacs 25.1-2, PHP CS Fixer 2.10.4 and v 1.0Beta1 of this elisp.

I can run `php-cs-fixer fix` with no problems from the command line.

When I execute `M-x php-cs-fixer-fix` from emacs I get this error(?) message:
```
Invalid rcs patch or internal error in php-cs-fixer--apply-rcs-patch
```

It looks like Emacs can find php-cs-fixer though, when I execute `M-! php-cs-fixer --version` it says:
```
PHP CS Fixer 2.10.4 Bowling Bear by Fabien Potencier and Dariusz Ruminski
```

When I look in `*Messages*` I can see that php-cs-fixer has written to a temporary file:
```
Wrote c:/Users/oskar/AppData/Local/Temp/PHP-CS-Fixer13520KIp.php
if: Invalid rcs patch or internal error in php-cs-fixer--apply-rcs-patch
```

When I diff that file to the same source file previous fixed with `php-cs-fixer fix` via the command line it seems that the temporary file has been fixed the same way, except that the temporary file has removed one `use` statement for a custom class. Could this be the problem? Or am I doing something else wrong here?

Do you need to see my source file?

**Comment by pivaldi** [comment]
Hi,

Yes, I would like to test your source file on my linux environment, please.

**Comment by fiskhandlarn** [comment]
@pivaldi All the files I have tested with results in the same message. Here is one of them:

```
<?php

declare(strict_types=1);

if (!defined('ABSPATH')) { exit(); }

global $normalizer;

if ( isset( $normalizer ) && $normalizer->compatible_version() ) {
    // also normalize acf fields
    add_filter('acf/update_value', function ($value) use ($normalizer) {
       if (is_string($value)) {
            return $normalizer->tl_normalizer($value);
        }

        return $value;
    });
}
```

`php-cs-fixer fix` still works from command line on the above file.

**Comment by fiskhandlarn** [comment]
@pivaldi Did you have a chance to look at this? :)

**Comment by pivaldi** [comment]
@fiskhandlarn 
Sorry I haven't a windows OS on hand. I must create a virtual machine and install all the deps for solving this problem…
I'll try to find time for that this week.

**Comment by fiskhandlarn** [comment]
@pivaldi bump :)

**Comment by pivaldi** [comment]
Hi…
I no longer use Emacs for coding, I switched to vscode.
I use now Emacs only for editing config file and for one shot rapid modification.
The is no chance that I fix this problem on Windows :(
Sorry :)

**Comment by fiskhandlarn** [comment]
My bad, the problem was that my Emacs tried to use another version of `diff` found in the global paths: https://github.com/prettier/prettier-emacs/issues/20#issuecomment-357197022 . It works perfect now!
