### ISSUE TITLE
How do I defined short array syntax?

### ISSUE THREAD

**Issue by echosa** [OVYA/php-cs-fixer#7]
How do I define this rule:

```
'array_syntax' => ['syntax' => 'short']
```

I've tried setting it in `Php Cs Fixer Rules Fixer Part Options`, but no matter what I try, it isn't working.

**Comment by pivaldi** [comment]
Hello @echosa ,

Personally, I've customized php-cs-fixer-config-option with the value `/home/pi/emacs.d/bin/php-cs-fixer-config.php`.
This file contains the following code : 
```php
#!/usr/bin/php
<?php

error_reporting(E_ALL | E_STRICT);

$finder = \PhpCsFixer\Finder::create()->in(__DIR__);

return \PhpCsFixer\Config::create()
    ->setRules([
        '@Symfony' => true,
        'array_syntax' => ['syntax' => 'short'],
        'no_multiline_whitespace_before_semicolons' => false,
        'concat_space' => ['spacing' => 'one'],
    ])->setFinder($finder);
```

I work on your problem as soon as possible.

Regards
